default_platform(:ios)

platform :ios do
  desc "Автоматическая сборка и отправка в TestFlight / App Store Connect"
  lane :beta do
    # Настройка API Ключа App Store Connect
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_API_KEY_BASE64"],
      is_key_content_base64: true
    )

    # Загрузка сборки в TestFlight
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end

  desc "Отправка готового билда в App Store на проверку модерации"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_API_KEY_BASE64"],
      is_key_content_base64: true
    )

    upload_to_app_store(
      api_key: api_key,
      force: true,
      skip_pdf: true,
      skip_metadata: false,
      skip_screenshots: true
    )
  end
end
